name: VirtualRyuugaku2
main: com.github.orgs.kotobaminers.virtualryuugaku.virtualryuugaku.VirtualRyuugaku
version: 0.1
commands:
  VRG:
  VIRTUALRYUUGAKU:
  TALKER:
  STAGE:
  VRGOP:
    permission: vertualryuugaku.op
  VIRTUALRYUUGAKUOP:
    permission: vertualryuugaku.op
  VRGDBG:
    permission: vertualryuugaku.op
  TALKEROP:
    permission: vertualryuugaku.op
  STAGEOP:
    permission: vertualryuugaku.op

permissions:
  vertualryuugaku.op:
    default: op