name: VirtualRyuugaku2
main: com.github.orgs.kotobaminers.virtualryuugaku.virtualryuugaku.VirtualRyuugaku
version: ${git.commit.id.describe}
commands:
  VIRTUALRYUUGAKU:
    usage: /vrg
    description: For more infomation /vrg
    aliases: [vrg, virtualryuugaku]
  VIRTUALRYUUGAKU_DEBUG:
    usage: /vrgd
    description: For more infomation /vrgd
    aliases: [vrgd]
  ANSWER:
    usage: /ans
    description: For more infomation /ans
    aliases: [ans, answer]
  VIRTUALRYUUGAKU_OP:
    usage: /vrgop
    description: For more infomation /vrgop
    aliases: [vrgop, virtualryuugakuop]