name: VirtualRyuugaku2
main: com.github.orgs.kotobaminers.virtualryuugaku.virtualryuugaku.VirtualRyuugaku
version: ${git.commit.id.describe}
commands:
  VIRTUALRYUUGAKU:
    aliases: [vrg, virtualryuugaku]
  ANSWER:
    aliases: [ans, answer]