name: VirtualRyuugaku2
main: com.gmail.fukushima.kai.virtualryuugaku2.virtualryuugaku2.VirtualRyuugaku2
version: 0.1
commands:
  NONE:
  VRG:
  VIRTUALRYUUGAKU:
  VRGOP:
  VIRTUALRYUUGAKUOP:
  VRGCO:
  STAGE:
  STAGEOP:
  TALKER:
  TALKEROP:
  SHADOW:
  SHADOWOP: