name: VirtualRyuugaku2
main: com.gmail.fukushima.kai.virtualryuugaku2.virtualryuugaku2.VirtualRyuugaku2
version: 0.1
commands:
  VRG:
  VIRTUALRYUUGAKU:
  TALKER:
  STAGE:
  VRGOP:
    permission: vertualryuugaku.op
  VIRTUALRYUUGAKUOP:
    permission: vertualryuugaku.op
  TALKEROP:
    permission: vertualryuugaku.op
  STAGEOP:
    permission: vertualryuugaku.op
  VRGCO:

permissions:
  vertualryuugaku.op:
    default: op